version: "3.8"

services:
  blog-backend:
    build: .
    image: blog-backend:1.2.3
    container_name: blog-backend
    restart: always

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      PORT: 3000
