version: "3.8"

services:
  blog-backend:
    build: .
    container_name: blog-backend
    restart: always

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      PORT: 3000

      DATABASE_URL: mysql://user:password@服务器线上ip:3366/blog

      JWT_SECRET: your_jwt_secret
